/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by vite-plugin-uni-pages

interface NavigateToOptions {
  url: "pages/index/index" |
       "pages/demo/index" |
       "pages/login/login" |
       "pages/my/index" |
       "pages/demo/demo/clock" |
       "pages/demo/demo/component-auto-import" |
       "pages/demo/demo/lottery" |
       "pages/demo/demo/lottery2" |
       "pages/demo/demo/mp-weixin-share" |
       "pages/demo/demo/navbar" |
       "pages/demo/demo/pages-auto-import" |
       "pages/demo/demo/pinia" |
       "pages/demo/demo/request" |
       "pages/demo/demo/throughout" |
       "pages/demo/demo/uni-ui-icons" |
       "pages/demo/demo/uni-ui" |
       "pages/demo/demo/unocss-icons" |
       "pages/demo/demo/unocss" |
       "pages/demo/demo/img-min/index" |
       "pages/demo/demo/lottery/big-wheel" |
       "pages/demo/demo/lottery/nine-grid" |
       "pages/demo/demo/throughout/index";
}
interface RedirectToOptions extends NavigateToOptions {}

interface SwitchTabOptions {
  url: 'pages/index/index' | 'pages/demo/index' | 'pages/my/index'
}

type ReLaunchOptions = NavigateToOptions | SwitchTabOptions

declare interface Uni {
  navigateTo(options: UniNamespace.NavigateToOptions & NavigateToOptions): void
  redirectTo(options: UniNamespace.RedirectToOptions & RedirectToOptions): void
  switchTab(options: UniNamespace.SwitchTabOptions & SwitchTabOptions): void
  reLaunch(options: UniNamespace.ReLaunchOptions & ReLaunchOptions): void
}
