import { color } from './color'

/**
 * 打印帮助信息
 */
export function printHelp(): void {
  console.log(color.green('\ncreate-unibest - 跨平台开发框架脚手架'))
  console.log('')
  console.log(color.blue('快速使用:'))
  console.log(color.green('  pnpm create unibest <command> [options]'))
  console.log(color.green('  pnpm create unibest my-project             创建新的unibest项目'))
  console.log(color.green('  pnpm create unibest add i18n               为已有项目添加i18n特性'))
  console.log(color.green('  pnpm create unibest add login              为已有项目添加login特性'))
  console.log(color.green('  pnpm create unibest add lime-echart        为已有项目添加lime-echart特性'))
  console.log(color.green('  pnpm create unibest add ucharts            为已有项目添加ucharts特性'))
  console.log(color.green('  pnpm create unibest -v                     查看版本信息'))
  console.log(color.green('  pnpm create unibest -h                     查看帮助信息'))
  console.log('')
  console.log(color.blue('可用命令:'))
  console.log(color.green('  <projectName>              创建项目'))
  console.log(color.green('  add <feature>              为已有项目添加 Feature'))
  console.log('')
  console.log(color.blue('创建项目选项:'))
  console.log(color.green('  -p, --platform <type>  指定平台 (h5, mp-weixin, app, mp-alipay, mp-toutiao)'))
  console.log(color.green('                         支持多选: -p h5,mp-weixin 或 -p h5 -p mp-weixin'))
  console.log(color.green('  -u, --ui <library>     指定UI库 (wot-ui, uview-pro, sard-uniapp, uv-ui, uview-plus, none)'))
  console.log(color.green('  -l, --login            是否需要登录策略'))
  console.log(color.green('  -i, --i18n             是否需要多语言'))
  console.log(color.green('  --lime-echart          添加 lime-echart 图表库（ECharts全端兼容）'))
  console.log(color.green('  --ucharts              添加 ucharts 图表库（秋云高性能跨平台）'))
  console.log(color.green('                         支持多选: --lime-echart --ucharts'))
  console.log('')
  console.log(color.blue('添加Feature选项:'))
  console.log(color.green('  <feature>              要添加的 Feature (i18n, login, lime-echart, ucharts)'))
  console.log(color.green('  --path <path>          项目路径 (默认当前目录)'))
  console.log(color.green('  --force                强制重新注入（覆盖已有配置）'))
  console.log('')
  console.log(color.blue('可用Feature:'))
  console.log(color.green('  i18n                   多语言支持'))
  console.log(color.green('  login                  登录策略（黑白名单、登录拦截等）'))
  console.log(color.green('  lime-echart            ECharts全端兼容图表库'))
  console.log(color.green('  ucharts                秋云高性能跨平台图表库'))
  console.log('')
  console.log(color.blue('示例:'))
  console.log(color.green('  # 创建项目'))
  console.log(color.green('  pnpm create unibest my-project -u wot-ui -p h5,mp-weixin'))
  console.log(color.green('  pnpm create unibest my-project -u uview-plus -l -i'))
  console.log(color.green('  pnpm create unibest my-project -u none -p h5,app,mp-weixin'))
  console.log(color.green('  pnpm create unibest my-project --lime-echart --ucharts  # 添加图表库'))
  console.log('')
  console.log(color.green('  # 添加 Feature'))
  console.log(color.green('  cd my-project && pnpm create unibest add i18n'))
  console.log(color.green('  pnpm create unibest add login --path /path/to/project'))
  console.log(color.green('  pnpm create unibest add i18n login'))
  console.log(color.green('  pnpm create unibest add i18n --force  # 重新注入'))
  console.log(color.green('  pnpm create unibest add lime-echart ucharts  # 添加图表库'))
  console.log('')
}
