#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

# Load nvm
export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm

# Use the correct Node.js version
# nvm use v20.15.1

# Run the pre-commit hook
npx --no-install -- lint-staged
